name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Doxygenとクラス図生成用のGraphviz（Dot）をインストール
      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile   # doxygenのコマンド引数にDoxyfileのパスを指定

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # Doxyfileの設定に合わせて、生成されたHTMLディレクトリを指定してArtifact化
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
